version: '3.7'

services:
  db:
    container_name: database
    image: postgres:12.4-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data:
